# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('settings', models.TextField(default='{\n  "schema": {\n    "title":"Describe the document",\n    "description":"The meta data associated with the document that was uploaded.",\n    "type":"object",\n    "properties": {\n\n      "document-name": {\n        "type":"string",\n        "title":"Document Name"\n      },\n\n      "date-published": {\n        "type":"string",\n        "title":"Date Published"\n      },\n\n      "publisher": {\n        "type":"string",\n        "title":"Publisher"\n      },\n\n      "institution": {\n        "type":"string",\n        "title":"institution"\n      },\n\n      "pi": {\n        "type":"string",\n        "title":"Principal Investigator"\n      },\n\n      "pi-email": {\n        "type":"string",\n        "title":"Principal Investigator Email"\n      },\n\n      "author-list": {\n        "type":"string",\n        "title":"Author(s)"\n      }\n    }\n  },\n\n\n  "options": {\n    "helper": "The meta data associated with the document that was uploaded.",\n    "fields": {\n\n      "document-name": {\n        "size": 256,\n        "helper": "Please enter the documents name.",\n        "placeholder": "documents name",\n        "focus" : false\n      },\n\n     "date-published": {\n       "format": "date-time",\n        "helper": "Please enter when the document was published.",\n        "placeholder": "e.g. 5/5/1995"\n      },\n\n     "publisher": {\n        "size": 256,\n        "helper": "Please enter the publisher.",\n        "placeholder": "Publisher"\n      },\n\n     "institution": {\n        "size": 256,\n        "helper": "Please enter the institution.",\n        "placeholder": "Institution"\n      },\n\n     "pi": {\n        "size": 156,\n        "helper": "Please enter the Principal Investigator.",\n        "placeholder": "e.g. John Doe"\n      },\n\n     "pi-email": {\n        "format": "email",\n        "size": 256,\n        "helper": "Please enter the Principal Investigator Email address.",\n        "placeholder": "e.g. JohnDoe@mail.com"\n      },\n\n     "author-list": {\n        "size": 256,\n        "helper": "Please enter the auther(s), if you have more than author use commas to separate them.",\n        "placeholder": "e.g. Cameron, Blandford Carolyn Stewart, Ryan Mason"\n      }\n\n    }\n  }\n};\n')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datesubmitted', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Untitled', max_length=300)),
                ('path', models.CharField(default='', max_length=50)),
            ],
            options={
                'permissions': (('view_document', 'View document'),),
            },
        ),
        migrations.CreateModel(
            name='Dynamicform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(default='')),
                ('answers', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='api.Department')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='api.Document')),
            ],
            options={
                'permissions': (('view_grant', 'View Grant'),),
            },
        ),
        migrations.CreateModel(
            name='Usertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[(1, 'researcher'), (2, 'moderator')], max_length=50)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='api.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamicforms', to='api.Grant'),
        ),
    ]
