# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='settings',
        ),
        migrations.AddField(
            model_name='department',
            name='settings',
            field=models.TextField(default='{\n  "schema": {\n    "title":"Describe the document",\n    "description":"The meta data associated with the document that was uploaded.",\n    "type":"object",\n    "properties": {\n\n      "document-name": {\n        "type":"string",\n        "title":"Document Name"\n      },\n\n      "date-published": {\n        "type":"string",\n        "title":"Date Published"\n      },\n\n      "publisher": {\n        "type":"string",\n        "title":"Publisher"\n      },\n\n      "institution": {\n        "type":"string",\n        "title":"institution"\n      },\n\n      "pi": {\n        "type":"string",\n        "title":"Principal Investigator"\n      },\n\n      "pi-email": {\n        "type":"string",\n        "title":"Principal Investigator Email"\n      },\n\n      "author-list": {\n        "type":"string",\n        "title":"Author(s)"\n      }\n    }\n  },\n\n\n  "options": {\n    "helper": "The meta data associated with the document that was uploaded.",\n    "fields": {\n\n      "document-name": {\n        "size": 256,\n        "helper": "Please enter the documents name.",\n        "placeholder": "documents name",\n        "focus" : false\n      },\n\n     "date-published": {\n       "format": "date-time",\n        "helper": "Please enter when the document was published.",\n        "placeholder": "e.g. 5/5/1995"\n      },\n\n     "publisher": {\n        "size": 256,\n        "helper": "Please enter the publisher.",\n        "placeholder": "Publisher"\n      },\n\n     "institution": {\n        "size": 256,\n        "helper": "Please enter the institution.",\n        "placeholder": "Institution"\n      },\n\n     "pi": {\n        "size": 156,\n        "helper": "Please enter the Principal Investigator.",\n        "placeholder": "e.g. John Doe"\n      },\n\n     "pi-email": {\n        "format": "email",\n        "size": 256,\n        "helper": "Please enter the Principal Investigator Email address.",\n        "placeholder": "e.g. JohnDoe@mail.com"\n      },\n\n     "author-list": {\n        "size": 256,\n        "helper": "Please enter the auther(s), if you have more than author use commas to separate them.",\n        "placeholder": "e.g. Cameron, Blandford Carolyn Stewart, Ryan Mason"\n      }\n\n    }\n  }\n};\n'),
        ),
        migrations.AddField(
            model_name='grant',
            name='status',
            field=models.CharField(choices=[(1, 'read'), (2, 'unread'), (3, 'archived')], default='unread', max_length=50),
            preserve_default=False,
        ),
    ]
