# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:16
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_link',
            field=models.FileField(upload_to=api.models.upload_to),
        ),
    ]
