# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:23
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160708_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_link', models.FileField(upload_to=api.models.upload_to)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_link',
        ),
    ]
