# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160708_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlink',
            name='uuid',
            field=models.CharField(default='', max_length=32),
        ),
    ]
