# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160712_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
