# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 15:29
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testlink_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testlink',
        ),
        migrations.AddField(
            model_name='document',
            name='file_link',
            field=models.FileField(default='', upload_to=api.models.upload_to),
        ),
        migrations.AddField(
            model_name='document',
            name='uuid',
            field=models.CharField(default='', max_length=32),
        ),
    ]
