# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='api.Department'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='usertype',
            field=models.CharField(choices=[(1, 'researcher'), (2, 'moderator')], max_length=50),
        ),
    ]
