# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datesubmitted', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Untitled', max_length=300)),
                ('path', models.CharField(default='', max_length=50)),
            ],
            options={
                'permissions': (('view_document', 'View document'),),
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=100)),
                ('status', models.TextField(default='New', max_length=160)),
                ('pistatus', models.TextField(default='New', max_length=160)),
                ('institutionstatus', models.TextField(default='New', max_length=160)),
                ('agencystatus', models.TextField(default='New', max_length=160)),
                ('schema', models.TextField(blank=True, default='{\n  "schema": {\n    "title":"Describe the document",\n    "description":"The meta data associated with the document that was uploaded.",\n    "type":"object",\n    "properties": {\n\n      "document-name": {\n        "type":"string",\n        "title":"Document Name"\n      },\n\n      "date-published": {\n        "type":"string",\n        "title":"Date Published"\n      },\n\n      "publisher": {\n        "type":"string",\n        "title":"Publisher"\n      },\n\n      "institution": {\n        "type":"string",\n        "title":"institution"\n      },\n\n      "pi": {\n        "type":"string",\n        "title":"Principal Investigator"\n      },\n\n      "pi-email": {\n        "type":"string",\n        "title":"Principal Investigator Email"\n      },\n\n      "author-list": {\n        "type":"string",\n        "title":"Author(s)"\n      }\n    }\n  },\n\n\n  "options": {\n    "helper": "The meta data associated with the document that was uploaded.",\n    "fields": {\n\n      "document-name": {\n        "size": 256,\n        "helper": "Please enter the documents name.",\n        "placeholder": "documents name",\n        "focus" : false\n      },\n\n     "date-published": {\n       "format": "date-time",\n        "helper": "Please enter when the document was published.",\n        "placeholder": "e.g. 5/5/1995"\n      },\n\n     "publisher": {\n        "size": 256,\n        "helper": "Please enter the publisher.",\n        "placeholder": "Publisher"\n      },\n\n     "institution": {\n        "size": 256,\n        "helper": "Please enter the institution.",\n        "placeholder": "Institution"\n      },\n\n     "pi": {\n        "size": 156,\n        "helper": "Please enter the Principal Investigator.",\n        "placeholder": "e.g. John Doe"\n      },\n\n     "pi-email": {\n        "format": "email",\n        "size": 256,\n        "helper": "Please enter the Principal Investigator Email address.",\n        "placeholder": "e.g. JohnDoe@mail.com"\n      },\n\n     "author-list": {\n        "size": 256,\n        "helper": "Please enter the auther(s), if you have more than author use commas to separate them.",\n        "placeholder": "e.g. Cameron, Blandford Carolyn Stewart, Ryan Mason"\n      }\n\n    },\n    "form": {\n        "buttons": {\n            "submit": {\n                "title": "Submit!"\n            }\n        }\n    }\n  }\n}', null=True)),
                ('metadata', models.TextField(blank=True, default='', null=True)),
                ('metadatarequested', models.BooleanField(default=False)),
                ('uploadrequested', models.BooleanField(default=False)),
                ('pi', models.TextField(max_length=10, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='api.Agency')),
                ('document', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='api.Document')),
            ],
            options={
                'permissions': (('view_grant', 'View Grant'), ('modify_grant', 'Modify Grant'), ('assign_grant_to_pi', 'Assign Grant to PI'), ('assign_grant_to_institution', 'Assign Grant to Institution')),
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='grant',
            name='institution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='api.Institution'),
        ),
    ]
